### PR TITLE
Bug/fix rotate authorities

### LINKED ISSUE #48: Bug: All aughorities has to vote again after authority rotation
Reproduction step:
Create a proposal in the Governance pallet. Have part of the council vote (e.g. A and B voted).
Rotate to a new set of authority that contains A and B

Expected: A and B's vote are kept.
Actual: All votes are cleared

We can keep the previous member's vote if they are still a member of the council.

### PR DESCRIPTION
**Pull request by IRISxiaowang**
Close #48 

Improved the function do_rotate_authorities()
Retain the votes if the new council member intersects with the old ones.
Added a test to ensure after changing authorities, the proposal can be voted on and resolved.

### CODE REVIEW

File: pallets/pallet-governance/src/lib.rs [hunk 1]
```diff
@@ -409,6 +409,25 @@ pub mod module {
...
+			// Identify old members
+			let old_members = CurrentAuthorities::<T>::get();
+
+			// Identify members to retain votes for
+			let members_to_retain: BTreeSet<_> =
+				unique_members.intersection(&old_members).cloned().collect();
+
+			if !members_to_retain.is_empty() {
+				for proposal_id in Votes::<T>::iter_keys() {
+					Votes::<T>::mutate(proposal_id, |casted| {
```
Comment (syan095) [inline pallets/pallet-governance/src/lib.rs:428]: this should be moved to an function in CasterVotes struct

File: pallets/pallet-governance/src/lib.rs [hunk 2]
```diff
@@ -409,6 +409,25 @@ pub mod module {
 			let unique_members: BTreeSet<_> = authorities.into_iter().collect();
 			CurrentAuthorities::<T>::set(unique_members.clone());
 
+			// Identify old members
+			let old_members = CurrentAuthorities::<T>::get();
```
Comment (syan095) [inline pallets/pallet-governance/src/lib.rs]: Should use mutate

**Review by syan095 — APPROVED** [review]
