### PR TITLE
fixed rotate-treasury()

### LINKED ISSUE #40: Bug: TreasuryAccount cannot be set
Reproduction steps: 
1. Start a local test chain
2. Observe the Treasury account is not set.
3. call function rotate_treasury(root, new_treasury) to set treasury

Expected result: 
new_treasury account is set successfully.

Actual result: 
TreasuryAccount is not set. new_treasury cannot be set successfully.

### PR DESCRIPTION
**Pull request by IRISxiaowang**
Close #40 

Fixed rotate_treasury(root, new_treasury), when the treasury account is not set, set it with the new_treasury account id.
Added test, make sure treasury account can be set successfully.

### CODE REVIEW

File: pallets/pallet-bank/src/lib.rs [hunk 1]
```diff
@@ -434,24 +434,40 @@ pub mod module {
...
-				});
-				// Update the storage map with the modified accounts
-				AccountWithUnlockedFund::<T>::insert(block_number, accounts);
-			});
+			ensure!(
+				T::RoleManager::role(&new_treasury).is_none(),
+				Error::<T>::AccountIdAlreadyTaken
+			);
+
+			let old_treasury = match Self::treasury() {
```
Comment (syan095) [inline pallets/pallet-bank/src/lib.rs]: I think it would be slightly better to use 
`let old_treasury = Self::treasury().ok()`
 to change from Result -> Option first
then
`if let Some(treasury) = old_treasury {
...
}`

**Review by syan095 — CHANGES_REQUESTED** [review]
just 1 minor improvement. Overall good

**Review by syan095 — APPROVED** [review]
LGTM
